### ISSUE TITLE
How to create aleMask and DynPesModel matrices

### ISSUE THREAD

**Issue by thuybinh** [lorisbaz/SDALF#7]
Dear Loris Bazzani, 
I want to run the source code on another dataset. However, I dont know the way to generate aleMask and DynPesModel matrices. Would you like to provide for me source code for these problem.
Thank you so much, 
BRgds, 
ThuyBinh Nguyen

**Comment by lorisbaz** [comment]
We did not release the code for generating the masks. You can find the masks for a bunch of datasets in the subfoder [MAT/](https://github.com/lorisbaz/SDALF/tree/master/MAT).

As alternative you can apply your own foreground method and still apply SDALF.
