### ISSUE TITLE
can't run the code

### ISSUE THREAD

**Issue by yashupian** [lorisbaz/SDALF#9]
dear author,
I can't run the code successfully. Some problems happen like "Bitshift ASSUMEDTYPE must be an integer type name." My matlab version is 2017b. There is some limitation for the matlab version?

**Comment by angleboy8** [comment]
I have the same problem. Do you have an answer.

**Comment by lorisbaz** [comment]
It has never been tested on that version of Matlab. The code is not really maintained anymore to comply with the latest version of Matlab. Let us know with a comment here, if you find a solution to the problem.
